# Generated by Django 4.2.6 on 2023-11-07 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('Alumni_ID', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10, null=True)),
                ('Email', models.CharField(max_length=20, null=True)),
                ('Address', models.CharField(max_length=20, null=True)),
                ('Contact_No', models.BigIntegerField(null=True)),
                ('minors', models.CharField(max_length=10, null=True)),
                ('Batch_id', models.CharField(max_length=10, null=True)),
                ('Position_id', models.CharField(max_length=10, null=True)),
                ('Donation_id', models.CharField(max_length=10, null=True)),
            ],
            options={
                'db_table': 'alumni',
            },
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_id', models.CharField(max_length=10)),
                ('position_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('application_deadline', models.DateField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.alumni')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='playground.position')),
            ],
        ),
    ]
